FIX: Fixes #26 Use config system to enable/disable FB cache-clearing
jonom/silverstripe-share-care pull request #29
Opened 2019-11-21 22:13 UTC by phptek

2019-11-21 22:14 UTC, phptek commented
Not sure why GIT thinks 14 files have changed. I set "filemode = false" in .git/config...

2019-11-25 19:22 UTC, jonom requested changes
@phptek thanks for this! Maybe your `filemode = false` needs to be `fileMode = false`. If that doesn't work can you just change the permissions back to 100644 for affected files?

2019-11-25 19:22 UTC, jonom commented on src/ShareCare.php
> +    private static $enable_facebook_cache_clear = false;
This needs to have a default value of true for backwards compatibility

2019-11-25 19:22 UTC, jonom commented on _config/ShareCare.yml
> +#   twitter_username: 'test-user'
Remove this change please (it's harmless but doesn't need to be here)

2019-11-25 19:22 UTC, jonom commented on README.md
> +Except:
Please change to:

```yml
JonoM\ShareCare\ShareCare:
  enable_facebook_cache_clear: false
---
Only:
  environment:
    - live
---
JonoM\ShareCare\ShareCare:
  enable_facebook_cache_clear: true
```

2019-11-28 20:00 UTC, phptek commented
Fixed-up the commit:

* Applied suggested edits
* Removed permission changes
* Force-pushed the feature branch

2019-12-11 20:52 UTC, phptek commented
@jonom any update on this? Thanks :-)

2019-12-12 20:05 UTC, merged

2019-12-12 20:28 UTC, jonom commented
Sorry for the delay @phptek! I've now tested and tagged 4.1 after tweaking the docs a little. Thanks for your contribution!